[package]
edition = "2024"
rust-version = "1.95.0"
name = "u2secure"
version = "0.2.0"
description = "Make your Linux system more secure through interactive CLI | 通过交互式的cli让你的Linux系统更安全"
readme = "README.md"
license = "MIT"
repository = "https://github.com/cherish-ltt/U2Secure"

[dependencies]
dialoguer = "0.12"
colored = "3"
chrono = "0.4.45"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.150"
anyhow = "1"
ctrlc = "3"
tempfile = "3"
ratatui = "0.30.1"
crossterm = "0.29"

[dev-dependencies]
tempfile = "3"
